### PR TITLE
added Death counter

### PR DESCRIPTION
**Pull request by DemonDezerin**

### CODE REVIEW

**Comment by LumixX-git** [comment]
GET OUT 🗣️🔥

**Comment by DemonDezerin** [comment]
No u

**Comment by LumixX-git** [comment]
Ok EDP445

**Comment by DemonDezerin** [comment]
I ain’t do nothing leave me alone

**Comment by LumixX-git** [comment]
I don't think touching little kids for pleasure is doing nothing bruv. Stop usin the issues tab as a chat room fag

**Comment by DemonDezerin** [comment]
Look who’s talking stfu I ain’t doing anything wrong leave me alone you son
of a bitch

**Comment by LumixX-git** [comment]
Yawn...........


Ironic considering everyone I talked to knows u a weirdo.....

Lemme just.... hit this button

**Pull request closed without merging**
